// This file is intentionally left blank.
// The service worker is now automatically generated by the VitePWA plugin during the build process.
// All configuration should be done in `vite.config.ts`.
