import { Section } from '../types';

export const etpSections: Section[] = [
  { id: 'etp-1-introducao', title: '1. Introdução', placeholder: 'Apresentação do objeto da contratação, da justificativa, do contexto e da forma da contratação...', hasGen: true, hasRiskAnalysis: true, tooltip: "Apresenta uma visão geral do que se pretende contratar, o porquê, e como a contratação se insere no contexto da Administração." },
  { id: 'etp-2-necessidade', title: '2. Descrição da Necessidade', placeholder: 'Detalhe a necessidade da contratação, o problema a ser resolvido, a perspectiva do interesse público...', hasGen: true, hasRiskAnalysis: true, tooltip: "Fundamento da contratação. Descreva o problema que precisa ser resolvido e a real necessidade da Administração que justifica a contratação. (Art. 18, § 1º, I, da Lei nº 14.133/21)." },
  { id: 'etp-3-requisitos', title: '3. Requisitos da Contratação', placeholder: 'Liste os requisitos essenciais e necessários ao atendimento da necessidade, como requisitos de negócio, legais, de segurança, etc.', hasGen: true, hasRiskAnalysis: true, tooltip: "Defina as condições e características mínimas que a solução deve ter para atender à demanda de forma satisfatória. (Art. 18, § 1º, III, da Lei nº 14.133/21)." },
  { id: 'etp-4-mercado', title: '4. Levantamento de Mercado', placeholder: 'Análise das alternativas possíveis e justificativa técnica e econômica da escolha do tipo de solução a contratar...', hasGen: true, hasRiskAnalysis: true, tooltip: "Pesquise e descreva as diferentes soluções disponíveis no mercado que podem atender à necessidade, justificando a escolha da mais adequada. (Art. 18, § 1º, V, da Lei nº 14.133/21)." },
  { id: 'etp-5-solucao', title: '5. Descrição da Solução como um Todo', placeholder: 'Descreva a solução escolhida, incluindo o ciclo de vida do objeto e as exigências de manutenção e assistência técnica, se for o caso.', hasGen: true, hasRiskAnalysis: true, tooltip: "Detalhe a solução escolhida, considerando todo o seu ciclo de vida, desde a aquisição até o descarte, incluindo manutenção e suporte. (Art. 18, § 1º, VII, da Lei nº 14.133/21)." },
  { id: 'etp-6-estimativas', title: '6. Estimativas das Quantidades', placeholder: 'Apresente as quantidades a serem contratadas, com memórias de cálculo e documentos de suporte...', hasGen: true, hasRiskAnalysis: true, tooltip: "Estime as quantidades necessárias para a contratação, com base em memória de cálculo e dados concretos, como consumo histórico. (Art. 18, § 1º, IV, da Lei nº 14.133/21)." },
  { id: 'etp-7-valor', title: '7. Estimativa do Valor da Contratação', placeholder: 'Apresente a estimativa de valor da contratação, com preços unitários, memórias de cálculo e a data-base da pesquisa...', hasGen: true, hasRiskAnalysis: true, tooltip: "Realize a pesquisa de preços e apresente o valor estimado da contratação, detalhando a metodologia e as fontes consultadas. (Art. 18, § 1º, VI, da Lei nº 14.133/21)." },
  { id: 'etp-8-parcelamento', title: '8. Justificativa para Parcelamento', placeholder: 'Justifique a decisão de parcelar ou não a solução em lotes, considerando a viabilidade técnica e econômica.', hasGen: true, hasRiskAnalysis: true, tooltip: "Demonstre se a contratação será feita em um único lote ou dividida em vários, justificando a decisão com base na viabilidade técnica e na busca por maior competitividade. (Art. 18, § 1º, VIII, da Lei nº 14.133/21)." },
  { id: 'etp-9-correlatas', title: '9. Contratações Correlatas/Interdependentes', placeholder: 'Liste outras contratações que impactam ou são impactadas por esta...', hasGen: true, hasRiskAnalysis: false, tooltip: "Identifique se esta contratação depende de outras ou se outras dependem dela, para garantir o alinhamento e evitar problemas de integração. (Art. 18, § 1º, XI, da Lei nº 14.133/21)." },
  { id: 'etp-10-alinhamento', title: '10. Alinhamento com o Planejamento', placeholder: 'Demonstre como a contratação está alinhada ao Plano de Contratações Anual e outros instrumentos de planejamento...', hasGen: true, hasRiskAnalysis: false, tooltip: "Mostre que a contratação está prevista nos instrumentos de planejamento do órgão (como o Plano de Contratações Anual), garantindo sua conformidade estratégica. (Art. 18, § 1º, II, da Lei nº 14.133/21)." },
  { id: 'etp-11-resultados', title: '11. Demonstrativo de Resultados', placeholder: 'Descreva os resultados pretendidos em termos de economicidade e melhor aproveitamento dos recursos...', hasGen: true, hasRiskAnalysis: true, tooltip: "Explicite os benefícios esperados com a contratação, como economia, eficiência, e melhor aproveitamento de recursos. (Art. 18, § 1º, IX, da Lei nº 14.133/21)." },
  { id: 'etp-12-providencias', title: '12. Providências Prévias', placeholder: 'Liste as ações que a Administração precisa tomar antes da celebração do contrato (ex: capacitação de fiscais, adequação de espaço)...', hasGen: true, hasRiskAnalysis: false, tooltip: "Relacione as medidas a serem adotadas pela Administração antes de assinar o contrato para garantir o sucesso da execução. (Art. 18, § 1º, X, da Lei nº 14.133/21)." },
  { id: 'etp-13-sustentabilidade', title: '13. Sustentabilidade', placeholder: 'Descreva os possíveis impactos ambientais e as medidas mitigadoras, incluindo requisitos de baixo consumo e logística reversa...', hasGen: true, hasRiskAnalysis: true, tooltip: "Aborde os aspectos de sustentabilidade da contratação, incluindo impactos ambientais e as medidas para mitigá-los. (Art. 18, § 1º, XII, da Lei nº 14.133/21)." },
  { id: 'etp-14-viabilidade', title: '14. Declaração de Viabilidade', placeholder: 'Apresente o posicionamento conclusivo sobre a adequação e viabilidade da contratação para atender à necessidade...', hasGen: true, hasRiskAnalysis: false, tooltip: "Conclua o estudo afirmando se a contratação é viável ou não, com base em toda a análise realizada. (Art. 18, § 1º, XIII, da Lei nº 14.133/21)." },
  { id: 'etp-15-anexos', title: '15. Anexos', placeholder: 'Liste aqui referências a documentos complementares ou adicione notas sobre os ficheiros anexados...', hasGen: false, tooltip: "Anexe documentos que suportam o ETP, como pesquisas de mercado, memórias de cálculo, etc.", isAttachmentSection: true }
];

export const trSections: Section[] = [
    { id: 'tr-1-objeto', title: '1. Objeto', placeholder: 'Definição do objeto, incluindo natureza, quantitativos, prazo do contrato e, se for o caso, a possibilidade de prorrogação...', hasGen: true, hasRiskAnalysis: true, tooltip: "Art. 6º, XXIII, 'a': Defina de forma precisa, suficiente e clara o que será contratado, incluindo quantidades e prazo." },
    { id: 'tr-2-justificativa', title: '2. Justificativa da Contratação', placeholder: 'Fundamentação da contratação, com referência aos estudos técnicos preliminares correspondentes...', hasGen: true, hasRiskAnalysis: true, tooltip: "Art. 6º, XXIII, 'b': Justifique a necessidade da contratação, referenciando o Estudo Técnico Preliminar (ETP) que a embasou." },
    { id: 'tr-3-natureza', title: '3. Natureza do Objeto', placeholder: 'Descreva se os serviços/bens são comuns ou especiais, se são contínuos ou por escopo, etc.', hasGen: true, hasRiskAnalysis: false, tooltip: "Classifique o objeto para definir o rito processual adequado (ex: bem/serviço comum geralmente leva a Pregão)." },
    { id: 'tr-4-execucao-requisitos', title: '4. Modelo de Execução e Requisitos', placeholder: 'Detalhe a forma de execução, rotinas, local, materiais, e outros requisitos técnicos para a perfeita execução do contrato...', hasGen: true, hasRiskAnalysis: true, tooltip: "Art. 6º, XXIII, 'd' e 'e': Descreva como, onde e quando o contrato será executado, e quais são os requisitos técnicos indispensáveis." },
    { id: 'tr-5-prazo-execucao', title: '5. Prazo de Execução dos Serviços', placeholder: 'Defina os prazos de início de etapas de execução, conclusão, entrega, observação e recebimento definitivo...', hasGen: true, hasRiskAnalysis: false, tooltip: "Art. 92, VII: Estabeleça o cronograma para a realização do objeto do contrato." },
    { id: 'tr-6-prazo-vigencia', title: '6. Prazo de Vigência do Contrato', placeholder: 'Defina o prazo de vigência do contrato, que pode ser diferente do prazo de execução...', hasGen: true, hasRiskAnalysis: false, tooltip: "Art. 105 a 114: Defina a duração total do vínculo contratual, observando os limites legais para cada tipo de objeto." },
    { id: 'tr-7-garantia', title: '7. Garantia Contratual', placeholder: 'Defina se será exigida garantia de execução do contrato e em quais moldes (percentual, modalidade).', hasGen: true, hasRiskAnalysis: false, tooltip: "Arts. 96 a 102: Especifique a necessidade e as condições da garantia que o contratado deverá apresentar para assegurar a plena execução do contrato." },
    { id: 'tr-8-obrigacoes', title: '8. Obrigações das Partes', placeholder: 'Liste as responsabilidades da Contratada e da Contratante...', hasGen: true, hasRiskAnalysis: true, tooltip: "Art. 92, XIV: Detalhe os deveres de cada parte para garantir clareza e segurança jurídica na execução contratual." },
    { id: 'tr-9-selecao-fornecedor', title: '9. Forma e Critérios de Seleção do Fornecedor', placeholder: 'Indique a modalidade de licitação (ex: Pregão) e o critério de julgamento (ex: Menor Preço).', hasGen: true, hasRiskAnalysis: false, tooltip: "Art. 6º, XXIII, 'h': Especifique como o fornecedor será selecionado, definindo a modalidade de licitação e o critério de julgamento." },
    { id: 'tr-10-qualificacao', title: '10. Requisitos de Habilitação', placeholder: 'Descreva os requisitos de qualificação jurídica, fiscal, social, trabalhista, técnica e econômico-financeira.', hasGen: true, hasRiskAnalysis: true, tooltip: "Arts. 62 a 70: Especifique os documentos e condições que os licitantes devem apresentar para comprovar que possuem capacidade de cumprir o contrato." },
    { id: 'tr-11-subcontratacao', title: '11. Da Subcontratação', placeholder: 'Defina se será permitida a subcontratação, em quais limites e condições.', hasGen: true, hasRiskAnalysis: false, tooltip: "Art. 122: Estabeleça as regras para a subcontratação de parte do objeto, caso seja permitida." },
    { id: 'tr-12-gestao-contrato', title: '12. Modelo de Gestão e Fiscalização', placeholder: 'Descreva como a execução do objeto será acompanhada e fiscalizada pela Administração...', hasGen: true, hasRiskAnalysis: false, tooltip: "Art. 6º, XXIII, 'f': Defina quem serão os fiscais do contrato e como será realizado o acompanhamento da execução." },
    { id: 'tr-13-medicao-pagamento', title: '13. Critérios de Medição e Pagamento', placeholder: 'Defina como os serviços serão medidos e quais os critérios e prazos para pagamento...', hasGen: true, hasRiskAnalysis: false, tooltip: "Art. 6º, XXIII, 'g': Estabeleça as regras para medir o que foi executado e como será feito o pagamento correspondente." },
    { id: 'tr-14-sancoes', title: '14. Sanções Administrativas', placeholder: 'Especifique as penalidades aplicáveis em caso de descumprimento do contrato...', hasGen: true, hasRiskAnalysis: false, tooltip: "Arts. 155 a 163: Determine as multas e outras sanções para o caso de inexecução total ou parcial do contrato." },
    { id: 'tr-15-sustentabilidade', title: '15. Sustentabilidade', placeholder: 'Descreva os critérios de sustentabilidade aplicáveis à contratação.', hasGen: true, hasRiskAnalysis: true, tooltip: "Art. 45 e outros: Incorpore requisitos de sustentabilidade ambiental, social e econômica na contratação." },
    { id: 'tr-16-orcamento', title: '16. Adequação Orçamentária', placeholder: 'Indique a dotação orçamentária que cobrirá a despesa...', hasGen: false, hasRiskAnalysis: false, tooltip: "Art. 6º, XXIII, 'j': Aponte o crédito orçamentário que suportará os custos da contratação." },
    { id: 'tr-17-anexos', title: '17. Anexos', placeholder: 'Liste aqui referências a documentos complementares ou adicione notas sobre os ficheiros anexados...', hasGen: false, tooltip: "Anexe documentos essenciais para a compreensão do TR, como o ETP (obrigatório), minutas de contrato, planilhas, etc.", isAttachmentSection: true }
];
