import { Template } from '../types';

export const etpTemplates: Template[] = [
  {
    id: 'etp-ti-equipment',
    name: 'Aquisição de Equipamentos de TI',
    description: 'Template para compra de computadores, notebooks, servidores ou outros equipamentos de informática.',
    type: 'etp',
    sections: {
      'etp-input-introducao': 'Este Estudo Técnico Preliminar (ETP) tem como objetivo planear e fundamentar a aquisição de novos equipamentos de tecnologia da informação para modernizar o parque tecnológico desta instituição, visando aumentar a produtividade e a segurança da informação.',
      'etp-input-demanda': 'A demanda atual surge da obsolescência dos equipamentos em uso, que possuem em média mais de 5 anos de utilização. Isso resulta em lentidão, falhas constantes, incompatibilidade com softwares modernos e riscos de segurança, afetando diretamente a performance dos colaboradores e a continuidade dos serviços.',
      'etp-input-analise-demanda': 'Foi realizado um levantamento interno que identificou 50 estações de trabalho com necessidade de substituição urgente. A análise de desempenho mostrou que o tempo de inicialização dos sistemas críticos é 40% maior nos equipamentos antigos em comparação com máquinas modernas. Além disso, os custos de manutenção corretiva aumentaram 25% no último ano.',
      'etp-input-levantamento-solucoes': 'Foram consideradas as seguintes soluções:\n1.  **Aquisição de Desktops:** Compra de computadores de mesa tradicionais.\n2.  **Aquisição de Notebooks:** Compra de computadores portáteis.\n3.  **Locação de Equipamentos (HaaS - Hardware as a Service):** Contratação de uma empresa que fornece e mantém os equipamentos por um período determinado.\n4.  **Virtualização de Desktops (VDI):** Implementação de uma infraestrutura onde os desktops são executados em servidores centralizados.',
      'etp-input-analise-solucoes': 'A aquisição de notebooks (Solução 2) apresenta o melhor custo-benefício, oferecendo mobilidade para o trabalho híbrido, que se tornou uma realidade na instituição. A locação (Solução 3) tem um custo total de propriedade maior a longo prazo. A VDI (Solução 4) exige um investimento inicial muito elevado em infraestrutura de servidores, o que é inviável no momento.',
      'etp-input-recomendacao': 'Recomenda-se a aquisição de 50 notebooks com especificações técnicas modernas, que atendam às necessidades de performance dos softwares utilizados pela instituição. Esta solução é a mais adequada por combinar performance, mobilidade e um custo de aquisição compatível com o orçamento disponível.',
      'etp-input-anexos': 'Anexo I - Pesquisa de Preços de Mercado.\nAnexo II - Planilha de Análise Comparativa de Soluções.',
    },
  },
  {
    id: 'etp-cleaning-services',
    name: 'Contratação de Serviços de Limpeza',
    description: 'Template para contratar serviços continuados de limpeza, conservação e higienização de áreas.',
    type: 'etp',
    sections: {
      'etp-input-introducao': 'O presente estudo visa fundamentar a contratação de empresa especializada na prestação de serviços continuados de limpeza, asseio e conservação predial, com fornecimento de mão de obra, saneantes domissanitários, materiais e equipamentos, para atender às necessidades das instalações desta instituição.',
      'etp-input-demanda': 'A demanda consiste na necessidade de manter um ambiente de trabalho limpo, higienizado e seguro para servidores e para o público externo, em conformidade com as normas de saúde e segurança do trabalho. O contrato atual está prestes a expirar, sendo imprescindível a nova contratação para não haver interrupção dos serviços.',
      'etp-input-analise-demanda': 'A área total a ser coberta pelos serviços é de 5.000 m², incluindo áreas administrativas, banheiros, áreas de circulação e áreas externas. A frequência e a produtividade foram calculadas com base nas diretrizes da IN SEGES/MP nº 5/2017, estimando-se a necessidade de 4 postos de trabalho em tempo integral.',
      'etp-input-levantamento-solucoes': '1. **Contratação de Empresa Especializada:** Modelo tradicional de terceirização dos serviços.\n2. **Execução Direta:** Contratação de pessoal próprio via concurso público para realizar os serviços.\n3. **Contratação por Empreitada de Mão de Obra:** Contratação apenas da mão de obra, com o órgão fornecendo os materiais e equipamentos.',
      'etp-input-analise-solucoes': 'A execução direta (Solução 2) é inviável devido às restrições orçamentárias e legais para novas contratações de pessoal. A contratação apenas da mão de obra (Solução 3) transfere para a Administração a complexa logística de compra e gestão de estoque de materiais. Portanto, a contratação de empresa especializada (Solução 1) é a mais eficiente, pois centraliza todas as responsabilidades no contratado.',
      'etp-input-recomendacao': 'Recomenda-se a contratação de empresa especializada para a prestação dos serviços de limpeza, conforme Solução 1, por ser o modelo que melhor atende à necessidade da Administração, otimizando a gestão e garantindo a qualidade e continuidade dos serviços.',
      'etp-input-anexos': 'Anexo I - Planilha de Dimensionamento da Equipe.\nAnexo II - Pesquisa de Mercado com Cotações.',
    },
  },
    {
    id: 'etp-software-dev',
    name: 'Desenvolvimento de Software Sob Demanda',
    description: 'Contratação de empresa para desenvolver um sistema web customizado para gestão de processos internos.',
    type: 'etp',
    sections: {
      'etp-input-introducao': 'Este ETP visa analisar a viabilidade e definir a melhor solução para a contratação de serviço de desenvolvimento de um novo Sistema de Gestão de Processos Internos (SGPI), a fim de automatizar fluxos de trabalho e centralizar informações.',
      'etp-input-demanda': 'A demanda decorre da ineficiência dos processos atuais, que dependem de planilhas eletrônicas e troca de e-mails. Isso gera retrabalho, perda de informações e dificuldade na geração de relatórios gerenciais, impactando a tomada de decisão.',
      'etp-input-analise-demanda': 'Um mapeamento de processos identificou que 80% das atividades administrativas são manuais e poderiam ser automatizadas. A estimativa é de uma redução de 30% no tempo gasto com tarefas operacionais, liberando os servidores para atividades mais estratégicas.',
      'etp-input-levantamento-solucoes': '1. **Desenvolvimento Interno:** Utilizar a equipe de TI própria para desenvolver o sistema.\n2. **Aquisição de Software de Prateleira (SaaS):** Contratar uma solução de mercado já existente.\n3. **Contratação de Fábrica de Software:** Contratar uma empresa especializada para desenvolver o sistema sob medida.',
      'etp-input-analise-solucoes': 'O desenvolvimento interno (Solução 1) é inviável pela equipe reduzida e falta de expertise específica. O software de prateleira (Solução 2) não atende a 60% dos requisitos específicos do nosso fluxo. A contratação de uma fábrica de software (Solução 3) permite a criação de uma solução 100% aderente às nossas necessidades.',
      'etp-input-recomendacao': 'Recomenda-se a contratação de empresa especializada (Fábrica de Software) para o desenvolvimento do SGPI, por ser a solução que garante a total aderência aos processos da instituição e oferece maior flexibilidade para futuras evoluções.',
      'etp-input-anexos': 'Anexo I - Mapeamento de Processos (AS-IS).\nAnexo II - Lista de Requisitos Funcionais e Não Funcionais.',
    },
  },
  {
    id: 'etp-consulting',
    name: 'Serviços de Consultoria Especializada',
    description: 'Template para contratar consultoria em gestão estratégica, financeira ou de processos.',
    type: 'etp',
    sections: {
        'etp-input-introducao': 'Este estudo preliminar objetiva fundamentar a contratação de serviços de consultoria especializada para elaboração do Planejamento Estratégico Institucional para o ciclo 2025-2030.',
        'etp-input-demanda': 'A instituição necessita de apoio técnico especializado para conduzir o processo de diagnóstico, formulação de objetivos, indicadores e metas estratégicas, garantindo uma metodologia moderna e participativa.',
        'etp-input-analise-demanda': 'O planejamento estratégico vigente encerra-se no final do ano. A ausência de um novo plano compromete a orientação das ações e a alocação de recursos para os próximos anos. A equipe interna não possui expertise na condução de um processo desta magnitude.',
        'etp-input-levantamento-solucoes': '1. **Capacitação da Equipe Interna:** Realizar cursos para que a própria equipe conduza o processo.\n2. **Contratação de Consultoria Especializada:** Terceirizar a condução metodológica do processo.\n3. **Criação de Grupo de Trabalho com Apoio Externo Pontual:** Formar uma equipe interna que contrate mentores para fases específicas.',
        'etp-input-analise-solucoes': 'A capacitação (Solução 1) demandaria muito tempo e não garantiria a experiência necessária. O modelo híbrido (Solução 3) poderia gerar descontinuidade. A contratação de consultoria (Solução 2) garante a aplicação de uma metodologia consolidada e a imparcialidade na condução dos trabalhos.',
        'etp-input-recomendacao': 'Recomenda-se a contratação de consultoria especializada em planejamento estratégico para o setor público, por ser a alternativa que assegura maior qualidade, agilidade e eficácia na entrega do produto final.',
        'etp-input-anexos': 'Anexo I - Relatório de Avaliação do Planejamento Estratégico Anterior.',
    },
  },
  {
    id: 'etp-public-event',
    name: 'Organização de Evento Público',
    description: 'Planejamento para a contratação de empresa para organizar uma conferência, seminário ou evento institucional.',
    type: 'etp',
    sections: {
        'etp-input-introducao': 'O presente ETP visa a contratação de empresa para organização completa do "1º Congresso Nacional de Inovação no Setor Público", incluindo planejamento, logística, infraestrutura e divulgação.',
        'etp-input-demanda': 'A demanda é realizar um evento de grande porte para 500 participantes, com o objetivo de disseminar boas práticas e promover o intercâmbio de conhecimento entre gestores públicos de todo o país.',
        'etp-input-analise-demanda': 'A instituição não possui estrutura interna (pessoal e material) para gerenciar um evento desta complexidade, que envolve a contratação de espaço, catering, equipamentos audiovisuais, passagens e hospedagem para palestrantes, entre outros.',
        'etp-input-levantamento-solucoes': '1. **Execução Direta por Comissão Interna:** Montar uma equipe de servidores para realizar todas as contratações fragmentadas.\n2. **Contratação de Empresa Organizadora de Eventos:** Centralizar toda a logística e produção em um único fornecedor.',
        'etp-input-analise-solucoes': 'A execução direta (Solução 1) sobrecarregaria os servidores, desviando-os de suas funções finalísticas, além de aumentar o risco de falhas pela falta de expertise. A contratação de empresa especializada (Solução 2) otimiza o processo, garante um padrão de qualidade profissional e centraliza a responsabilidade.',
        'etp-input-recomendacao': 'É recomendada a contratação de uma empresa com notória especialização em organização de eventos corporativos e públicos para garantir o sucesso do Congresso, desde a concepção até a execução final.',
        'etp-input-anexos': 'Anexo I - Pré-programação do Evento.\nAnexo II - Estimativa de Custos Detalhada.',
    },
  },
];

export const trTemplates: Template[] = [
  {
    id: 'tr-notebooks',
    name: 'Aquisição de Notebooks',
    description: 'Modelo detalhado para a compra de computadores portáteis para uso institucional.',
    type: 'tr',
    sections: {
      'tr-input-objeto': 'Aquisição de 50 (cinquenta) notebooks, conforme especificações técnicas, condições e prazos estabelecidos neste Termo de Referência e seus anexos. O prazo de garantia mínimo exigido é de 24 (vinte e quatro) meses on-site.',
      'tr-input-justificativa': 'A presente contratação justifica-se pela necessidade de modernização do parque computacional, em substituição a equipamentos obsoletos e com baixo desempenho, conforme detalhado no Estudo Técnico Preliminar nº XXX/2024. A aquisição visa prover aos servidores ferramentas de trabalho adequadas, promovendo maior agilidade, mobilidade e segurança no desempenho de suas atividades.',
      'tr-input-execucao': 'A entrega dos equipamentos deverá ser realizada em parcela única, no prazo máximo de 30 (trinta) dias corridos, contados a partir do recebimento da Nota de Empenho. Os notebooks deverão ser entregues no Almoxarifado Central desta instituição, localizado no endereço [endereço completo], em dias úteis, no horário das 8h às 17h. Todos os equipamentos devem ser novos, de primeiro uso, e entregues em suas embalagens originais lacradas.',
      'tr-input-obrigacoes': '**Obrigações da CONTRATADA:**\n- Entregar os equipamentos em perfeito estado de funcionamento e em conformidade com as especificações deste Termo.\n- Prestar a garantia técnica de 24 meses, on-site, com atendimento em até 48 horas úteis.\n- Fornecer toda a documentação fiscal e técnica dos produtos.\n\n**Obrigações da CONTRATANTE:**\n- Realizar o recebimento provisório e definitivo dos bens.\n- Efetuar o pagamento no prazo e condições estabelecidas.\n- Notificar a contratada sobre quaisquer defeitos ou irregularidades.',
      'tr-input-habilitacao': 'A licitante deverá apresentar Atestado de Capacidade Técnica, emitido por pessoa jurídica de direito público ou privado, que comprove ter fornecido bens de natureza e vulto compatíveis com o objeto desta licitação. Deverá também apresentar declaração do fabricante, ou documento equivalente, assegurando que é revenda autorizada.',
      'tr-input-pagamento': 'O pagamento será efetuado em parcela única, no prazo de até 30 (trinta) dias após o recebimento definitivo dos equipamentos, mediante a apresentação da correspondente nota fiscal devidamente atestada pelo fiscal do contrato. A despesa correrá à conta da dotação orçamentária: [Número da Dotação Orçamentária].',
      'tr-input-fiscalizacao': 'A gestão e fiscalização do contrato serão realizadas por servidor(a) ou comissão designada pela autoridade competente, que será responsável por acompanhar a entrega, atestar o recebimento dos equipamentos e comunicar quaisquer ocorrências à Administração.',
      'tr-input-sancoes': 'O descumprimento total ou parcial das obrigações assumidas sujeitará a contratada às sanções previstas no Capítulo II do Título IV da Lei nº 14.133/2021, garantido o contraditório e a ampla defesa.',
      'tr-input-anexos': 'Anexo I - Especificações Técnicas Mínimas dos Notebooks.\nAnexo II - Minuta do Contrato.',
    },
  },
  {
    id: 'tr-security-services',
    name: 'Serviços de Vigilância Patrimonial',
    description: 'Modelo para contratar serviços continuados de vigilância armada e/ou desarmada.',
    type: 'tr',
    sections: {
        'tr-input-objeto': 'Contratação de empresa especializada para a prestação de serviços continuados de vigilância patrimonial armada, visando à cobertura dos postos e escalas definidos neste Termo de Referência, para garantir a segurança das instalações, servidores e bens da instituição.',
        'tr-input-justificativa': 'A contratação é essencial para assegurar a integridade do patrimônio público e a segurança da comunidade interna, prevenindo furtos, roubos e outros atos ilícitos. A necessidade está fundamentada no ETP nº YYY/2024, que analisou os riscos e a vulnerabilidade das instalações.',
        'tr-input-execucao': 'Os serviços serão prestados de forma ininterrupta, 24 horas por dia, 7 dias por semana, incluindo feriados, através da alocação de 3 (três) postos de vigilância armada, em regime de escala 12x36h. A empresa deverá fornecer profissionais devidamente habilitados, uniformizados e equipados com colete balístico, rádio comunicador e armamento legalizado.',
        'tr-input-obrigacoes': '**Obrigações da CONTRATADA:**\n- Manter a cobertura completa de todos os postos de serviço, sem interrupções.\n- Assegurar que todos os vigilantes possuam a Carteira Nacional de Vigilante (CNV) e cursos de reciclagem em dia.\n- Cumprir rigorosamente a legislação trabalhista e previdenciária aplicável aos seus empregados.\n\n**Obrigações da CONTRATANTE:**\n- Proporcionar as condições adequadas para a execução dos serviços nos postos.\n- Efetuar os pagamentos mensais mediante a comprovação da regularidade fiscal e trabalhista da contratada.',
        'tr-input-habilitacao': 'A licitante deverá possuir Autorização de Funcionamento e Certificado de Segurança expedidos pela Polícia Federal. Deverá comprovar, mediante atestados, ter executado serviços de vigilância patrimonial armada por um período mínimo de 3 anos.',
        'tr-input-pagamento': 'O pagamento será mensal, realizado após o término do mês de prestação dos serviços e condicionado à apresentação da documentação comprobatória de quitação das obrigações trabalhistas e previdenciárias, conforme a IN SEGES/MP nº 5/2017.',
        'tr-input-fiscalizacao': 'A fiscalização do contrato será exercida por um gestor e fiscais designados, que verificarão a assiduidade, a apresentação pessoal dos vigilantes, o estado dos equipamentos e o cumprimento das normas de segurança estabelecidas.',
        'tr-input-sancoes': 'Falhas na cobertura dos postos, apresentação de vigilantes desarmados ou sem a devida documentação, entre outras irregularidades, sujeitarão a contratada a advertências, multas e, em caso de reincidência, à rescisão contratual, conforme Lei nº 14.133/21.',
        'tr-input-anexos': 'Anexo I - Planilha de Custos e Formação de Preços.\nAnexo II - Relação de Postos e Escalas.',
    },
  },
  {
    id: 'tr-cloud-saas',
    name: 'Assinatura de Serviços em Nuvem (SaaS)',
    description: 'Modelo para contratar uma plataforma de software como serviço, como CRM, ERP ou ferramenta de colaboração.',
    type: 'tr',
    sections: {
        'tr-input-objeto': 'Contratação de serviço de assinatura de plataforma de Software como Serviço (SaaS) para gestão de projetos, incluindo 100 (cem) licenças de usuário, suporte técnico e atualizações contínuas, pelo período de 12 (doze) meses.',
        'tr-input-justificativa': 'A contratação é necessária para padronizar e otimizar o gerenciamento de projetos na instituição, conforme apontado no ETP nº ZZZ/2024. A solução em nuvem elimina a necessidade de infraestrutura local e garante acesso remoto seguro para as equipes.',
        'tr-input-execucao': 'O serviço deverá ser disponibilizado em até 5 (cinco) dias úteis após a assinatura do contrato. A contratada deverá fornecer treinamento inicial para os usuários e garantir um Acordo de Nível de Serviço (SLA) de 99,8% de disponibilidade da plataforma. O suporte técnico deverá ser oferecido em português, em horário comercial.',
        'tr-input-obrigacoes': '**Obrigações da CONTRATADA:**\n- Manter a plataforma funcional e disponível, conforme SLA.\n- Realizar backups diários dos dados.\n- Garantir a segurança da informação e a conformidade com a Lei Geral de Proteção de Dados (LGPD).\n\n**Obrigações da CONTRATANTE:**\n- Utilizar o serviço de acordo com os termos de uso.\n- Efetuar o pagamento mensal da assinatura.',
        'tr-input-habilitacao': 'A licitante deverá comprovar experiência na prestação de serviços SaaS, apresentando atestados de capacidade técnica. Deverá também apresentar certificações de segurança da informação, como ISO 27001, ou equivalente.',
        'tr-input-pagamento': 'O pagamento será mensal e recorrente, realizado até o 10º dia útil do mês subsequente à prestação do serviço, mediante apresentação de nota fiscal.',
        'tr-input-fiscalizacao': 'A fiscalização será realizada por um gestor de contrato, que irá monitorar o cumprimento do SLA, a qualidade do suporte e a satisfação dos usuários por meio de relatórios mensais e pesquisas periódicas.',
        'tr-input-sancoes': 'O descumprimento do SLA acordado implicará em glosa no pagamento mensal, proporcional ao tempo de indisponibilidade, sem prejuízo da aplicação de outras sanções por falhas graves no serviço.',
        'tr-input-anexos': 'Anexo I - Requisitos Técnicos e Funcionais da Plataforma.\nAnexo II - Acordo de Nível de Serviço (SLA).',
    },
  },
  {
    id: 'tr-vehicle-fleet',
    name: 'Terceirização de Frota de Veículos',
    description: 'Contratação de serviços de locação de veículos com manutenção e seguro inclusos para uso institucional.',
    type: 'tr',
    sections: {
        'tr-input-objeto': 'Contratação de empresa para prestação de serviço de locação de 10 (dez) veículos tipo sedan, zero quilômetro, com motorização mínima de 1.6, ar condicionado, direção assistida, incluindo manutenção preventiva e corretiva, seguro total e carro reserva.',
        'tr-input-justificativa': 'A terceirização da frota, conforme ETP nº ABC/2024, é mais vantajosa economicamente do que a aquisição e manutenção de frota própria, eliminando custos com depreciação, manutenção, seguro e gestão de multas. Visa atender às necessidades de deslocamento de servidores em serviço.',
        'tr-input-execucao': 'Os veículos deverão ser entregues em até 30 dias após a assinatura do contrato. A contratada deverá disponibilizar um canal de atendimento 24h para emergências. A manutenção preventiva será realizada conforme o manual do fabricante, em local e horário agendados sem prejuízo ao serviço.',
        'tr-input-obrigacoes': '**Obrigações da CONTRATADA:**\n- Fornecer os veículos nas especificações contratadas.\n- Realizar todas as manutenções e arcar com os custos de seguro e documentação.\n- Disponibilizar carro reserva em até 24 horas em caso de pane ou sinistro.\n\n**Obrigações da CONTRATANTE:**\n- Utilizar os veículos para fins exclusivamente institucionais.\n- Responsabilizar-se por multas de trânsito decorrentes de infrações dos condutores.',
        'tr-input-habilitacao': 'A licitante deverá comprovar possuir frota compatível com o objeto, por meio de documentação dos veículos (CRLV). Deverá apresentar atestados de capacidade técnica para serviço de locação de frotas para órgãos públicos ou empresas privadas.',
        'tr-input-pagamento': 'O pagamento será fixo e mensal, por veículo, conforme o valor da proposta vencedora.',
        'tr-input-fiscalizacao': 'A fiscalização será realizada pelo setor de transportes, que controlará o uso dos veículos, o agendamento de manutenções e o acionamento de seguros, atestando a fatura mensal.',
        'tr-input-sancoes': 'Atraso na entrega dos veículos ou na disponibilização do carro reserva sujeitará a contratada a multas diárias. Falhas recorrentes na manutenção poderão levar à rescisão do contrato.',
        'tr-input-anexos': 'Anexo I - Especificações Mínimas dos Veículos.\nAnexo II - Minuta do Contrato.',
    },
  },
  {
    id: 'tr-training',
    name: 'Capacitação e Treinamento Especializado',
    description: 'Contratação de curso ou treinamento específico para servidores, com instrutor e material didático.',
    type: 'tr',
    sections: {
        'tr-input-objeto': 'Contratação de serviço de capacitação, na modalidade presencial, do curso "Gestão e Fiscalização de Contratos sob a ótica da Lei 14.133/21", com carga horária de 24 horas, para uma turma de 30 (trinta) servidores, incluindo material didático e certificação.',
        'tr-input-justificativa': 'A contratação é fundamental para capacitar os servidores que atuam como gestores e fiscais de contratos, adequando seus conhecimentos à nova legislação de licitações e contratos, a fim de mitigar riscos e aumentar a eficiência administrativa, conforme ETP nº DEF/2024.',
        'tr-input-execucao': 'O curso deverá ser realizado nas instalações da Contratante, em datas a serem acordadas, no prazo de até 60 dias após a assinatura do contrato. A contratada deverá fornecer instrutor com comprovada experiência na matéria e todo o material didático (apostilas e slides) para os participantes.',
        'tr-input-obrigacoes': '**Obrigações da CONTRATADA:**\n- Ministrar o curso conforme o conteúdo programático aprovado.\n- Fornecer instrutor qualificado e material didático de qualidade.\n- Emitir certificados para os participantes com frequência mínima de 75%.\n\n**Obrigações da CONTRATANTE:**\n- Disponibilizar sala de aula adequada com recursos audiovisuais.\n- Efetuar o pagamento após a conclusão do serviço.',
        'tr-input-habilitacao': 'A licitante deverá apresentar currículo detalhado do(s) instrutor(es) proposto(s), comprovando notório saber e experiência em licitações e contratos públicos. Deverá também apresentar atestados de capacidade técnica de cursos similares ministrados para outros órgãos públicos.',
        'tr-input-pagamento': 'O pagamento será realizado em parcela única, após a conclusão do curso e a entrega dos certificados, mediante apresentação da nota fiscal devidamente atestada pelo fiscal do contrato.',
        'tr-input-fiscalizacao': 'A fiscalização será exercida por um servidor designado, que acompanhará a realização do curso, verificará a frequência dos participantes, a qualidade do material e a didática do instrutor, e atestará a execução do serviço.',
        'tr-input-sancoes': 'O não cumprimento da carga horária, a alteração do conteúdo programático sem prévia autorização ou a substituição do instrutor por outro de qualificação inferior são passíveis de multa e outras sanções.',
        'tr-input-anexos': 'Anexo I - Conteúdo Programático Detalhado do Curso.\nAnexo II - Currículo Mínimo do Instrutor.',
    },
  },
];
